# Generated by Django 3.1 on 2020-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
                ('size', models.CharField(max_length=100, null=True, verbose_name='文件大小')),
                ('file', models.FileField(upload_to='', verbose_name='地址')),
                ('times', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
    ]
